sonar.projectKey=buddygpt
sonar.projectName=buddygpt
sonar.projectVersion=1.0

sonar.sources=app/src/main/java
sonar.java.binaries=app/build/intermediates/javac/debug/classes

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.apk,**/*.zip,**/*.png,**/*.jpg,**/*.svg

sonar.host.url=http://localhost:9000
sonar.login=sqp_7f17b6b2f6cfe79343372687c46bfc895f3b52e0
